import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

/// The computed quality score for a single focus session.
/// Decomposed into four environmental sub-scores (0–100 each).
class FocusScore {
  final double total;         // overall weighted score 0-100
  final double lightScore;    // ambient light quality
  final double noiseScore;    // acoustic environment quality
  final double movementScore; // physical disturbance score
  final double durationScore; // session length bonus

  /// Human-readable insights generated by the scoring engine.
  final List<String> positives;
  final List<String> negatives;
  final List<String> recommendations;

  const FocusScore({
    required this.total,
    required this.lightScore,
    required this.noiseScore,
    required this.movementScore,
    required this.durationScore,
    this.positives = const [],
    this.negatives = const [],
    this.recommendations = const [],
  });

  /// Letter grade A–F.
  String get grade {
    if (total >= 85) return 'A';
    if (total >= 70) return 'B';
    if (total >= 55) return 'C';
    if (total >= 40) return 'D';
    return 'F';
  }

  /// Short label displayed on cards and reports.
  String get label {
    if (total >= 85) return 'Excellent';
    if (total >= 70) return 'Good';
    if (total >= 55) return 'Moderate';
    if (total >= 40) return 'Poor';
    return 'Disrupted';
  }

  /// Colour that communicates score quality at a glance.
  Color get color => AppTheme.scoreColor(total);

  Map<String, dynamic> toJson() => {
        'total': total,
        'lightScore': lightScore,
        'noiseScore': noiseScore,
        'movementScore': movementScore,
        'durationScore': durationScore,
        'positives': positives,
        'negatives': negatives,
        'recommendations': recommendations,
      };

  factory FocusScore.fromJson(Map<String, dynamic> j) => FocusScore(
        total: (j['total'] as num).toDouble(),
        lightScore: (j['lightScore'] as num).toDouble(),
        noiseScore: (j['noiseScore'] as num).toDouble(),
        movementScore: (j['movementScore'] as num).toDouble(),
        durationScore: (j['durationScore'] as num).toDouble(),
        positives: List<String>.from(j['positives'] ?? []),
        negatives: List<String>.from(j['negatives'] ?? []),
        recommendations: List<String>.from(j['recommendations'] ?? []),
      );
}
